import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import 'rc-pagination/assets/index.css';
import React from 'react';
import HeaderComponent from './components/layouts/header/HeaderComponent';
import FooterComponent from './components/layouts/footer/FooterComponent';
import { ToastContainer } from 'react-toastify';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['200', '100', '300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className='scroll-smooth bg-gray-100'>
      <body suppressHydrationWarning={true} className={poppins.className}>
        <HeaderComponent />
        <main>{children}</main>
        <FooterComponent />
        <ToastContainer />
      </body>
    </html>
  );
}
